# Site settings
title: Galesburg Community Chorus
email: galesburgchorusmanager@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 The Galesburg Community Chorus is proud to be celebrating their 74th
 season of bringing outstanding choral works to the residents of Western
 Illinois.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.galesburgchorus.org/" # the base hostname & protocol for your site
# twitter_username: jekyllrb

# Build settings
markdown: kramdown
