# Site settings
title: Galesburg Community Chorus
email: chorusmanager@centurylink.net
description: > # this means to ignore newlines until "baseurl:"
 The Galesburg Community Chorus is proud to be celebrating their 70th
 season of bringing outstanding choral works to the residents of Western
 Illinois.
 <p/>
 This program is partially supported by a grant from the <a href="http://www.arts.illinois.gov/">Illinois Arts Council Agency</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.galesburgchorus.org/" # the base hostname & protocol for your site
# twitter_username: jekyllrb

# Build settings
markdown: kramdown
